[workspace]
members = [
    "apps/desktop/src-tauri",
    "crates/contracts",
    "crates/ssh-core",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/baoxue2026/bx-ssh"
rust-version = "1.91"

[workspace.dependencies]
bx-contracts = { path = "crates/contracts" }
bx-ssh-core = { path = "crates/ssh-core" }
russh = { version = "0.62.5", default-features = false, features = ["flate2", "ring", "rsa"] }
serde = { version = "1.0.229", features = ["derive"] }
tauri = { version = "2.11.5" }
tauri-build = { version = "2.6.3" }
thiserror = { version = "2.0.19" }
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread", "sync", "time"] }
uuid = { version = "1.18.1", features = ["v4"] }

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true
