/* eslint-disable */
// @ts-nocheck
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async appInfo() : Promise<AppInfo> {
    return await TAURI_INVOKE("app_info");
},
async readClipboardText() : Promise<Result<string, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_clipboard_text") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async writeClipboardText(text: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_clipboard_text", { text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openExternalUrl(url: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_external_url", { url }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async probeSshHost(request: ProbeHostRequest) : Promise<Result<HostKeyInfo, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("probe_ssh_host", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getKnownHost(host: string, port: number) : Promise<Result<HostKeyInfo | null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_known_host", { host, port }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async trustHostFingerprint(request: TrustHostFingerprintRequest) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("trust_host_fingerprint", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async writeTerminal(sessionId: string, data: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_terminal", { sessionId, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resizeTerminal(sessionId: string, columns: number, rows: number, pixelWidth: number, pixelHeight: number) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resize_terminal", { sessionId, columns, rows, pixelWidth, pixelHeight }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async acknowledgeTerminalOutput(sessionId: string, sequence: number) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("acknowledge_terminal_output", { sessionId, sequence }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async closeTerminalSession(sessionId: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("close_terminal_session", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async respondKeyboardInteractive(attemptId: string, responses: string[]) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("respond_keyboard_interactive", { attemptId, responses }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listSftpDirectory(sessionId: string, path: string) : Promise<Result<RemoteDirectoryListing, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_sftp_directory", { sessionId, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async uploadSftpFile(sessionId: string, localPath: string, remotePath: string, language: string) : Promise<Result<TransferSummary, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("upload_sftp_file", { sessionId, localPath, remotePath, language }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async downloadSftpFile(sessionId: string, remotePath: string, localPath: string, language: string) : Promise<Result<TransferSummary, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_sftp_file", { sessionId, remotePath, localPath, language }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hashRemoteSftpFile(sessionId: string, remotePath: string) : Promise<Result<TransferSummary, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("hash_remote_sftp_file", { sessionId, remotePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async closeSftpSession(sessionId: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("close_sftp_session", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setWebviewMemoryUsage(low: boolean) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_webview_memory_usage", { low }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkForUpdate() : Promise<Result<UpdateInfo | null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_for_update") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async confirmAppExit() : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("confirm_app_exit") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listConnections() : Promise<Result<ConnectionCatalog, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_connections") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getConnection(id: string) : Promise<Result<ConnectionDetails | null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_connection", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveConnection(config: ConnectionConfig, settings: ConnectionSettingsOverride) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_connection", { config, settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPasswordCredential(credentialRef: string) : Promise<Result<string | null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_password_credential", { credentialRef }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async savePasswordCredential(credentialRef: string, password: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_password_credential", { credentialRef, password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deletePasswordCredential(credentialRef: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_password_credential", { credentialRef }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteConnection(id: string) : Promise<Result<boolean, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_connection", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async recordSuccessfulConnection(id: string) : Promise<Result<boolean, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("record_successful_connection", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveConnectionGroup(group: ConnectionGroup) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_connection_group", { group }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteConnectionGroup(id: string) : Promise<Result<boolean, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_connection_group", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setConnectionGroupCollapsed(id: string, isCollapsed: boolean) : Promise<Result<boolean, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_connection_group_collapsed", { id, isCollapsed }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async reorderConnectionGroups(ids: string[]) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reorder_connection_groups", { ids }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setConnectionFavorite(id: string, isFavorite: boolean) : Promise<Result<boolean, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_connection_favorite", { id, isFavorite }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async reorderConnections(groupId: string | null, ids: string[]) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reorder_connections", { groupId, ids }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async previewOpensshConfig(path: string | null) : Promise<Result<OpenSshImportPreview, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_openssh_config", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importOpensshConnections(request: OpenSshImportRequest) : Promise<Result<OpenSshImportResult, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_openssh_connections", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelSshConnection(attemptId: string) : Promise<Result<boolean, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_ssh_connection", { attemptId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AppInfo = { name: string; version: string }
export type AppMenuAction = "show-terminal" | "show-sftp" | "check-for-updates"
export type AuthMethod = "password" | "privateKey" | "keyboardInteractive"
export type CommandError = { code: CommandErrorCode; message: string; stage: SshConnectionStage | null }
export type CommandErrorCode = "invalid_host" | "invalid_port" | "invalid_username" | "invalid_fingerprint" | "invalid_terminal_size" | "invalid_remote_path" | "invalid_local_file" | "local_target_exists" | "remote_target_exists" | "transfer_integrity_mismatch" | "connect_timeout" | "dns_lookup_timeout" | "dns_lookup_failed" | "tcp_connect_timeout" | "connection_refused" | "network_unreachable" | "tcp_connect_failed" | "handshake_timeout" | "handshake_failed" | "connection_cancelled" | "invalid_connection_attempt" | "connection_attempt_conflict" | "session_state_invalid" | "authentication_timeout" | "host_key_unavailable" | "host_key_mismatch" | "authentication_rejected" | "legacy_rsa_signature_only" | "channel_request_rejected" | "channel_closed" | "keep_alive_failed" | "private_key_error" | "sftp_error" | "transfer_io_error" | "transport_error" | "session_not_found" | "session_closed" | "terminal_output_unavailable" | "update_not_available" | "update_changed" | "update_signature_invalid" | "update_insecure_endpoint" | "update_unavailable" | "update_failed" | "webview_memory_usage_failed" | "database_unavailable" | "database_query_failed" | "credential_store_locked" | "credential_store_unavailable" | "credential_store_failed" | "invalid_credential" | "clipboard_unavailable" | "invalid_external_url" | "external_link_open_failed" | "open_ssh_config_not_found" | "open_ssh_config_io_error" | "open_ssh_config_invalid"
export type ConnectionCatalog = { groups: ConnectionGroup[]; connections: ConnectionListItem[] }
export type ConnectionConfig = { id: string; groupId: string | null; name: string; host: string; port: number; username: string; notes: string | null; color: string | null; authMethod: AuthMethod; credentialRef: string | null; keyReferenceId: string | null }
export type ConnectionDetails = { connection: ConnectionListItem; settings: ConnectionSettingsSnapshot }
export type ConnectionGroup = { id: string; name: string; color: string | null; sortOrder: number; isCollapsed: boolean; revision: number }
export type ConnectionListItem = { config: ConnectionConfig; isFavorite: boolean; sortOrder: number; lastConnectedAt: number | null; successfulConnectionCount: number; revision: number }
export type ConnectionSettings = { connectTimeoutSecs: number; keepAliveSecs: number }
export type ConnectionSettingsLayers = { global: ConnectionSettingsOverride | null; group: ConnectionSettingsOverride | null; connection: ConnectionSettingsOverride | null }
export type ConnectionSettingsOverride = { connectTimeoutSecs: number | null; keepAliveSecs: number | null }
export type ConnectionSettingsScope = { kind: "global" } | { kind: "group"; groupId: string } | { kind: "connection"; connectionId: string }
export type ConnectionSettingsSnapshot = { layers: ConnectionSettingsLayers; resolved: ConnectionSettings }
export type ExitImpact = { activeSessions: number; activeTransfers: number }
export type HostKeyInfo = { algorithm: string; fingerprintSha256: string }
export type KeyboardInteractiveEvent = { type: "prompt"; attemptId: string; name: string; instructions: string; prompts: KeyboardInteractivePromptItem[] }
export type KeyboardInteractivePromptItem = { prompt: string; echo: boolean }
export type OpenSshDuplicateStrategy = "skip" | "overwrite"
export type OpenSshImportError = "invalidPort" | "missingHost" | "missingUsername"
export type OpenSshImportItem = { sourceId: string; alias: string; host: string; port: number; username: string; identityFile: string | null; duplicateConnectionId: string | null; duplicateConnectionName: string | null; errors: OpenSshImportError[]; warnings: OpenSshImportWarning[] }
export type OpenSshImportPreview = { sourcePath: string; sourceFingerprint: string; items: OpenSshImportItem[]; ignoredHostPatterns: number }
export type OpenSshImportRequest = { sourcePath: string; sourceFingerprint: string; selectedSourceIds: string[]; duplicateStrategy: OpenSshDuplicateStrategy }
export type OpenSshImportResult = { imported: number; overwritten: number; skipped: number }
export type OpenSshImportWarning = "duplicate" | "identityFileRequiresKeySetup"
export type ProbeHostRequest = { host: string; port: number; settings: ConnectionSettings }
export type RemoteDirectoryListing = { path: string; entries: RemoteFileEntry[] }
export type RemoteFileEntry = { name: string; path: string; kind: RemoteFileKind; size: number; modifiedAt: number | null; permissions: number | null }
export type RemoteFileKind = "directory" | "file" | "symlink" | "other"
export type SshConnectionEvent = { attemptId: string; stage: SshConnectionStage }
export type SshConnectionStage = "created" | "resolvingDns" | "connectingTcp" | "handshaking" | "authenticating" | "openingChannel" | "connected" | "closing" | "closed" | "cancelled" | "failed"
export type StartKeyboardInteractiveShellRequest = { attemptId: string; host: string; port: number; username: string; expectedFingerprint: string; settings: ConnectionSettings; columns: number; rows: number; pixelWidth: number; pixelHeight: number }
export type StartPrivateKeySftpRequest = { attemptId: string; host: string; port: number; username: string; keyReferenceId: string; passphrase: string | null; expectedFingerprint: string; settings: ConnectionSettings; initialPath: string | null }
export type StartPrivateKeyShellRequest = { attemptId: string; host: string; port: number; username: string; keyReferenceId: string; passphrase: string | null; expectedFingerprint: string; settings: ConnectionSettings; columns: number; rows: number; pixelWidth: number; pixelHeight: number }
export type StartSftpRequest = { attemptId: string; host: string; port: number; username: string; password: string; expectedFingerprint: string; settings: ConnectionSettings; initialPath: string | null }
export type StartSftpResponse = { sessionId: string; hostKey: HostKeyInfo; directory: RemoteDirectoryListing }
export type StartShellRequest = { attemptId: string; host: string; port: number; username: string; password: string; expectedFingerprint: string; settings: ConnectionSettings; columns: number; rows: number; pixelWidth: number; pixelHeight: number }
export type StartShellResponse = { sessionId: string; hostKey: HostKeyInfo }
export type TerminalEvent = { type: "exited"; code: number | null; signal: string | null } | { type: "error"; code: CommandErrorCode; message: string }
export type TransferSummary = { bytes: number; elapsedMs: number; bytesPerSecond: number; sha256: string }
export type TrustHostFingerprintRequest = { host: string; port: number; hostKey: HostKeyInfo }
export type UpdateEvent = { type: "started"; contentLength: number | null } | { type: "progress"; chunkLength: number } | { type: "verified" }
export type UpdateInfo = { currentVersion: string; version: string; notes: string | null; publishedAt: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
